name: safesecurelibs
description: "A Flutter package for checking device security status, including root detection, developer mode, and dangerous apps."

version: 2.1.2+3

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.libsec.securesafelibs
        pluginClass: SafeSecureLibPlugin # Ubah nama class